export const SET_USER = 'SET_USER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const MEDIAS_REQUEST = 'MEDIAS_REQUEST';
export const MEDIAS_SUCCESS = 'MEDIAS_SUCCESS';
export const MEDIAS_FAILURE = 'MEDIAS_FAILURE';

export const MEDIA_REQUEST = 'MEDIA_REQUEST';
export const MEDIA_SUCCESS = 'MEDIA_SUCCESS';
export const MEDIA_FAILURE = 'MEDIA_FAILURE';