export const USER_SUCCESS = 'USER_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER = 'SET_USER';
export const ON_LOGIN_FORM_FIELD_CHANGE = 'ON_LOGIN_FORM_FIELD_CHANGE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const ON_REGISTER_FORM_FIELD_CHANGE = 'ON_REGISTER_FORM_FIELD_CHANGE';

export const MEDIA_LIKE = 'MEDIA_LIKE';
export const MEDIA_FAVORITE = 'MEDIA_FAVORITE';

export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE';
export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
export const INVALIDATE_COMMENT = 'INVALIDATE_COMMENT';

export const FAVORITES_SUCCESS = 'FAVORITES_SUCCESS';
export const FAVORITES_REQUEST = 'FAVORITES_REQUEST';
export const FAVORITES_FAILURE = 'FAVORITES_FAILURE';


export const DOWNLOADS_SUCCESS = 'DOWNLOADS_SUCCESS';
export const DOWNLOADS_REQUEST = 'DOWNLOADS_REQUEST';
export const DOWNLOADS_FAILURE = 'DOWNLOADS_FAILURE';

export const MEDIAS_SUCCESS = 'MEDIAS_SUCCESS';
export const MEDIAS_REQUEST = 'MEDIAS_REQUEST';
export const MEDIAS_FAILURE = 'MEDIAS_FAILURE';

export const MEDIA_SUCCESS = 'MEDIA_SUCCESS';
export const MEDIA_REQUEST = 'MEDIA_REQUEST';
export const MEDIA_FAILURE = 'MEDIA_FAILURE';